### ISSUE TITLE
keyword `fps` is no longer supported in the new version of imageIO

### ISSUE THREAD

**Issue by AkexStar** [YannDubs/Neural-Process-Family#11]
`imageio.mimsave(save_filename, figs, fps=fps)`
line 150 in https://github.com/YannDubs/Neural-Process-Family/blob/master/utils/visualize/helpers.py

if you pip install the newest imageio, then it will not work
In my test, imageio==2.20 works

**Comment by YannDubs** [comment]
thanks for flagging this, could you share the error you had?

my guess is that the issue is the same as : https://github.com/imageio/imageio/issues/973

**Comment by AkexStar** [comment]
@YannDubs 
Yes, much like this issue. It did appear in`mimsave`

---
P.S.
And I'm trying to implement ConvLNP on topographic maps. I want to enhance the resolution by NPF.
I note that you have published a paper ([arXiv:2007.01332](https://arxiv.org/abs/2007.01332)) on the European terrain. 
Do you have any codes/Repos recommendations? I would be most grateful if you could let me know!

**Comment by YannDubs** [comment]
I pined imageio<=2.27, let me know if it works now!

concerning the topographic maps, are you asking for the code to replicate those results I'm not sure we ever released that code, but @andrewfoongyk  would know better (sorry it's been a while)

**Comment by andrewfoongyk** [comment]
The code for training on weather data over Europe is indeed in a private repository; we don't currently have plans to release that publicly.

**Comment by AkexStar** [comment]
> I pined imageio<=2.27, let me know if it works now!
> 
> concerning the topographic maps, are you asking for the code to replicate those results I'm not sure we ever released that code, but @andrewfoongyk would know better (sorry it's been a while)

@YannDubs 
It works!
Thank your for this fix~

@andrewfoongyk 
Ok, I will try to have another try. And thanks for reply
