### ISSUE TITLE
[Question] ConvCNP in more than 1 spatial dimension

### ISSUE THREAD

**Issue by alexmaraval** [YannDubs/Neural-Process-Family#9]
Thanks for the amazing repo and its related website, I'm enjoying learning about the NPF :)

This issue is more of a general question rather than a specific problem.

I am wondering if it is possible to use the [`ConvCNP`](https://github.com/YannDubs/Neural-Process-Family/blob/master/npf/neuralproc/convnp.py#L26) model for regression with inputs `x` of dimension larger than 1. I notice that the [`SetConv`](https://github.com/YannDubs/Neural-Process-Family/blob/master/npf/architectures/setcnn.py#L226) layer produces an error if we initialize it with `x_dim` larger than 1. 

Also from the [paper](https://arxiv.org/pdf/1910.13556.pdf) it should be possible to replicate the experiment on the PLAsTiCC dataset but as far as I understand this experiment is set up as a multi-input-multi-output, i.e. you'd have a 6d input and 6d output.

Is there a way to have for example a 6d input but only a 1d output using this repo? And is there a way to do that off-grid?

**Comment by YannDubs** [comment]
If you remove the assertion [here](https://github.com/YannDubs/Neural-Process-Family/blob/0b0f84a9c7bd218c8752e949bc61f8b2e7f822cd/npf/architectures/setcnn.py#L226) and use `RadialBasisFunc=MlpRBF` (or implement `ExpRBF` for multidimensional `x_dim`) it should work although I never tested it.

You might also want to look at: https://github.com/cambridge-mlg/convcnp (original repo for off-the0grid results in that paper ) and https://github.com/wesselb/neuralprocesses
